[secrets]
FIREBASE_TYPE = "service_account"
FIREBASE_PROJECT_ID = "mysc-resource-management-a98c9"
FIREBASE_PRIVATE_KEY_ID = ""abc123...""
FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC..."
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-xxxxx@mysc-resource-management-a98c9.iam.gserviceaccount.com"
FIREBASE_CLIENT_ID = "123456789"
FIREBASE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
FIREBASE_TOKEN_URI = "https://oauth2.googleapis.com/token"
FIREBASE_AUTH_PROVIDER_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
FIREBASE_CLIENT_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-xxxxx%40mysc-resource-management-a98c9.iam.gserviceaccount.com"
